### ISSUE TITLE
advanced shipping module needs to be updated

### ISSUE THREAD

**Issue by gregplaysguitar** [sonsandco/django-shoptools#12]
This module should be simplified so it just provides admin-configurable shipping options and doesn't include region and country data, since this is now handled by the regions app. It also needs to be updated according to the shipping API

**Comment by gregplaysguitar** [comment]
Note https://github.com/sonsandco/django-shoptools/blob/master/cart/actions.py#L76

**Comment by gregplaysguitar** [comment]
Hey @pbright , this all looks good, a couple of things

- I'd like to keep the region app decoupled from shipping, so I don't think we should have shipping-related inlines in the region admin. 
- available_options was meant to be able to return multiple options, is there a reason you changed that?


Otherwise all looks sensible.

**Comment by pbright** [comment]
- I agree on the decoupling, but it's pretty messy in the admin unless they're an inline on the region. I could do it all in the shipping module by deregistering RegionAdmin, adding the inline and then registering it, but that felt dirty. 

- Sorry, should have asked you about that. I can change it so that it's:
      return { 
          'postage': ((o.id, o.name) for o in region.shipping_options.all()) 
      }
Is that what you had in mind? What's the use case you were thinking of here? I guess it makes sense for gift wrap and gift card options to be part of the shipping options (and we don't have options on the Order, only OrderLines, so I'm not sure where else they would go).

I still need to go through and update all other modules' interface with the shipping api, including the cart action you linked to above.

**Comment by gregplaysguitar** [comment]
> it's pretty messy in the admin unless they're an inline on the region. 

Fair enough, but let's keep shipping admin stuff in the shipping app. I would just register Region again under shipping, with the shipping inlines, all the Region fields readonly and a link back to the actual region admin to edit them. (This way it's clear there's only one "Region" model)

> I can change it so that it's:
>     return {
>          'postage': ((o.id, o.name) for o in region.shipping_options.all())
>      }
> Is that what you had in mind?

Yup that's right. I don't have a specific use-case in mind, but there doesn't seem to be any reason to limit it to one? It's only slightly more complicated and it gives us the flexibility going forward.

**Comment by pbright** [comment]
Let me know if you're happy with the Soohyang implementation and if so I'll pull it in.
