### ISSUE TITLE
Country default for region

### ISSUE THREAD

**Issue by pbright** [sonsandco/django-shoptools#24]
Currently we have an is_default field for Region and a class method to get the default.

Don't we need the same on Country? Otherwise when a user changes region the initial selection of country is a bit arbitrary. 

Looks like it's in there but commented out currently.

**Comment by gregplaysguitar** [comment]
Why does the user need to select their country? In general I don't think the site needs to know what country they're in, because pricing etc doesn't vary on a country level.

Also, it shouldn't select an arbitrary country, it should just set country to None - see 

https://github.com/sonsandco/django-shoptools/blob/master/shoptools/contrib/regions/util.py#L96

**Comment by pbright** [comment]
Hmm, yes I guess you're right. We only use it for the address.

Currently regions.util.set_region doesn't set country to None, should we do that? Otherwise a subsequent call to regions_data (for example) will return a country and region that don't match up.

**Comment by gregplaysguitar** [comment]
I think we should just not set the country in the session at all since we're not using it - if/when we get a site where setting user country is required we can think through the logic then

So just comment out these lines?

https://github.com/sonsandco/django-shoptools/blob/master/shoptools/contrib/regions/util.py#L117-L119

**Comment by pbright** [comment]
Fine by me.
